# production docker-compose
    

version: '3.8'
services:

  # DB
  db:
    build: ./db
    volumes:
      - db-dv:/var/lib/postgresql/data

  # app
  app:
    build: ./app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi
    volumes:
      - static-dv:/usr/src/app/static/
      - log-dv:/usr/src/app/logs/
    expose:
      - 8000
    depends_on:
      - db

  # web
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    volumes:
      - static-dv:/usr/share/nginx/html/static/
      - media-dv:/usr/share/nginx/html/media/
    depends_on:
      - app

volumes:
  db-dv:
  static-dv:
  media-dv:
  log-dv:
