# development docker-compose


version: '3.8'
services:

    # DB
    db:
        build: ./db
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
        volumes:
            - db-dv:/var/lib/postgresql/data

    # app
    app:
        build: ./app
        environment:
            - DJANGO_SETTINGS_MODULE
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./app:/usr/src/app
        ports:
            - 8000:8000
        depends_on:
            - db 

volumes:
    db-dv:
